# Generated by Django 2.2.2 on 2019-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
