# Generated by Django 2.2.3 on 2019-07-21 22:09

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meyer', '0002_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='background'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='css_class',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='meyer.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='css_class',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
