# Generated by Django 2.2.2 on 2019-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyer', '0004_auto_20190731_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
