# Generated by Django 2.2.2 on 2020-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyer', '0005_topic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mobile_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
